DROP TABLE IF EXISTS UsersFlags;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Flags;

CREATE TABLE Users (
    id INT NOT NULL AUTO_INCREMENT,
    publicId VARCHAR(64) NOT NULL,
    name VARCHAR(24) NOT NULL,
    email VARCHAR(32) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE Flags (
    id INT NOT NULL AUTO_INCREMENT,
    host VARCHAR(32) NOT NULL,
    tag VARCHAR(32) NOT NULL,
    value INT NOT NULL,
    comment VARCHAR(128),
    PRIMARY KEY (id)
);

CREATE TABLE UsersFlags (
    uId INT NOT NULL,
    fId INT NOT NULL,
    ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (uId) REFERENCES Users (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (fId) REFERENCES Flags (id) ON UPDATE CASCADE ON DELETE CASCADE
);